package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	"fmt"
	"study-gator-backend/graph/model"
)

// ID is the resolver for the id field.
func (r *studyGroupResolver) ID(ctx context.Context, obj *model.StudyGroup) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// Posts is the resolver for the posts field.
func (r *studyGroupResolver) Posts(ctx context.Context, obj *model.StudyGroup, limit int, offset int) ([]*model.Post, error) {
	panic(fmt.Errorf("not implemented: Posts - posts"))
}

// StudyGroup returns StudyGroupResolver implementation.
func (r *Resolver) StudyGroup() StudyGroupResolver { return &studyGroupResolver{r} }

type studyGroupResolver struct{ *Resolver }
