name: Backend

on: 
  push:
    branches:
      - main

jobs:
  build-and-deploy:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Run Go Tidy
        run: export PATH=$PATH:/usr/local/go/bin && cd backend && go mod tidy
      - name: Run Golang Tests
        run: export PATH=$PATH:/usr/local/go/bin && cd backend && go test
      - name: Build
        run: export PATH=$PATH:/usr/local/go/bin && cd backend && go build -o main
      - name: Move and Install
        run: cd backend && rm /home/chase/server/main && mv ./main /home/chase/server && sudo systemctl restart studygator
